List<String> shepherdList = [
  "Eld. Godfrey Kofi Saim",
  "Eld. Francis Kofi Annor",
  "Eld. Felix Kwame Ametor",
  "Eld. Isaac Amoh",
  "Eld. Ernest Kofi Antwi",
  "Eld. Richard Siaw",
  "Eld. Gordon Owusu Mensah",
  "Eld. Charles Ampofo",
  "Dcns. Dorothy Delali Acheampong",
  "Dcns. Leticia Aidoo",
  "Dcns. Grace Obeng",
  "Dcns. Grace Antwi",
  "Dcns. Cynthia Asare",
  "Dcns. Deborah Asiedu",
  "Dcns. Mercy Abeyie",
  "Dcn. Charles Hadjor",
  "Eld. Isaac Fiakpornu",
  "Dcns. Abigail Deedei Adu",
  "Deacon Mark Ekow Tawiah",
  "Eld. Jeremiah Dzorkpe-Yevenyo",
  "Dcn. Daniel Annor Boateng",
  "N/A",
];

List positionHeldList = [
  'Pastor (Ps)',
  'Presiding Elder (P.E)',
  'Elder (Eld)',
  'Deacon (Dcn)',
  'Deaconess (Dcns)',
  'Member (M)',
];

List connectGroupList = [
  "Elohim",
  "Rapha",
  "Nissi",
  "Shalom",
  "Jireh",
  "El-Shaddai",
  "Shammah",
  "Adonai",
  "Elyon",
  "Tsidkenu",
];
