// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCE7DWFonBVRigcgD_dvg0Kxz12PKv_YF4',
    appId: '1:680528639207:web:de84852101672a74f1de42',
    messagingSenderId: '680528639207',
    projectId: 'ddea-web',
    authDomain: 'ddea-web.firebaseapp.com',
    databaseURL: 'https://ddea-web-default-rtdb.firebaseio.com',
    storageBucket: 'ddea-web.appspot.com',
    measurementId: 'G-V837TEKNN6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBXb4Bh7HUekBLTkftttrSt9aC7Y0kCac',
    appId: '1:680528639207:android:dc3dddb6b21b7908f1de42',
    messagingSenderId: '680528639207',
    projectId: 'ddea-web',
    databaseURL: 'https://ddea-web-default-rtdb.firebaseio.com',
    storageBucket: 'ddea-web.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhagiJtDzA24jvL6brtFoQpbAXBPZRoWg',
    appId: '1:680528639207:ios:a08e2e692112cb97f1de42',
    messagingSenderId: '680528639207',
    projectId: 'ddea-web',
    databaseURL: 'https://ddea-web-default-rtdb.firebaseio.com',
    storageBucket: 'ddea-web.appspot.com',
    iosClientId: '680528639207-qkcln444tl2kn9j7dpl466msrji75v2b.apps.googleusercontent.com',
    iosBundleId: 'com.example.ddeaWeb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhagiJtDzA24jvL6brtFoQpbAXBPZRoWg',
    appId: '1:680528639207:ios:02d3089e69926609f1de42',
    messagingSenderId: '680528639207',
    projectId: 'ddea-web',
    databaseURL: 'https://ddea-web-default-rtdb.firebaseio.com',
    storageBucket: 'ddea-web.appspot.com',
    iosClientId: '680528639207-l9uvi2nue7cf37kmtbkcdtll1q50vm5j.apps.googleusercontent.com',
    iosBundleId: 'com.example.ddeaWeb.RunnerTests',
  );
}
